# 🏗️ STAGE 1: Build mit Maven
FROM eclipse-temurin:17-jdk AS builder
WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests -B

# 🧼 STAGE 2: Distroless Runtime
FROM gcr.io/distroless/java17-debian11
WORKDIR /app

COPY --from=builder /app/target/dockerapp-0.0.1-SNAPSHOT.jar /app/app.jar

# 🔒 Sicherer Benutzer
USER nonroot

CMD ["/app/app.jar"]




# 🚀 Image bauen:
# docker build -f ./dockerfiles/Dockerfile.distroless -t myimage:distroless .

# docker run -d --name mycontainer-distroless --env-file .env.dev -p 8083:8080 myimage:distroless
